name: release ci
on:
  push:
    tags:
      - '*'
    branches:
      - bc-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      SQUIRREL_BUNDLED_RECIPES: 'lotem/rime-octagram-data lotem/rime-octagram-data@hant'
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          ref: bc-branch
          submodules: true

      - name: Install clang-format
        run: brew install clang-format

      - name: Lint
        run: make clang-format-lint

      - name: Build Squirrel
        run: ./action-build.sh archive

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package/*.zip"
          draft: true
          token: ${{ secrets.ACCESS_TOKEN }}

